seed_init: 62
num_runs: 1
benchmark: fashionmnist_10p_non_iid
network_type: MLP
use_cuda: true
num_epochs_batch: 0
num_clients: 10
num_comm_rounds: 50
federated_method: FedIVON
learning_rate_local: 0.00003
batch_size: 32
h0_local: 0.0005
temperature: 0.001
local_prior_prec: 0.1
dual_update_damping: 0.001
federated_step_size: 0.2
beta2_local: 0.9998
use_scheduler: True
clipradius_local: inf
dual_update_damping_multiply_Nk_N: 0
extra_weightdecay: 0
num_epochs_local: 10
init_at_zero: False
use_model_merging_style_global_update: False
wandb_log: False
log_interval_epochs: 1000
plot_comm_round: 0
hidden_sizes: [200, 100]