seed_init: 62
num_runs: 1
benchmark: cifar10_non_iid
network_type: FedDynCifarCNN
opt_type: Adam
grad_clip: 10
use_cuda: true
global_prior_prec: 0
num_epochs_batch: 0
batch_size: 64
num_clients: 10
num_comm_rounds: 50
federated_method: FedLap
federated_step_size: 20
dual_update_damping: 0.1
dual_update_damping_multiply_Nk_N: 0
local_prior_prec: 0
global_step_size: 1
num_epochs_local: 10
learning_rate_local: 0.0001
plot_comm_round: 0
log_interval_epochs: 10