seed_init: 62
num_runs: 1
benchmark: hetmnist_non_iid
network_type: MLP
use_cuda: true
num_epochs_batch: 0
num_clients: 100
num_comm_rounds: 100
federated_method: FedIVON
learning_rate_local: 0.02
batch_size: 32
h0_local: 0.005
temperature: 0.01
local_prior_prec: 0.01
dual_update_damping: 0.1
federated_step_size: 5.0
beta2_local: 0.9998
use_scheduler: True
clipradius_local: inf
dual_update_damping_multiply_Nk_N: 0.0
extra_weightdecay: 0.0
num_epochs_local: 10.0
init_at_zero: False
use_model_merging_style_global_update: False
wandb_log: False
log_interval_epochs: 1000
plot_comm_round: 0
hidden_sizes: [200, 100]
  
