seed_init: 62
num_runs: 1
benchmark: cifar100_non_iid
network_type: ResNet20
use_cuda: true
num_epochs_batch: 0
num_clients: 10
num_comm_rounds: 100
federated_method: FedIVON
learning_rate_local: 0.001
batch_size: 64
h0_local: 0.1
temperature: 0.1
local_prior_prec: 0.5
dual_update_damping: 0.1
federated_step_size: 0.5
beta2_local: 0.99999
use_scheduler: True
clipradius_local: inf
dual_update_damping_multiply_Nk_N: 0.0
extra_weightdecay: 0
num_epochs_local: 25
init_at_zero: False
use_model_merging_style_global_update: False
wandb_log: False
log_interval_epochs: 0
plot_comm_round: 0
testmcsamples: 0